/**
 * Mock data for Sociocultural Indicators
 * Simulates state-level and national data for demonstration
 */

export const STATES = [
  "Lagos",
  "Kano",
  "Katsina",
  "Rivers",
  "Oyo",
  "Enugu",
  "Osun",
  "Kwara",
  "Bauch",
  "Borno",
];

// Gender comparison data (percentages or hours)
export const GENDER_COMPARISON_DATA = [
  {
    name: "NIN Enrollment",
    female: 45,
    male: 55,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Mobile Ownership",
    female: 62,
    male: 78,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Smartphone Ownership",
    female: 38,
    male: 52,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Cash Transfer Recipients",
    female: 28,
    male: 22,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Pension Access",
    female: 15,
    male: 25,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Micropension Access",
    female: 35,
    male: 40,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Unpaid Domestic Work (hrs/day)",
    female: 4.5,
    male: 1.2,
    female_label: "Female",
    male_label: "Male",
  },
  {
    name: "Migration Abroad",
    female: 12,
    male: 18,
    female_label: "Female",
    male_label: "Male",
  },
];

// State-level gender comparison data
export const STATE_GENDER_DATA = [
  {
    state: "Lagos",
    nin_female: 68,
    nin_male: 75,
    mobile_female: 85,
    mobile_male: 92,
    smartphone_female: 52,
    smartphone_male: 68,
    cash_transfer_female: 35,
    cash_transfer_male: 28,
    pension_female: 22,
    pension_male: 35,
    micropension_female: 45,
    micropension_male: 52,
    unpaid_work_female: 3.2,
    unpaid_work_male: 0.8,
    migration_female: 18,
    migration_male: 25,
    land_ownership_female: 25,
  },
  {
    state: "Kano",
    nin_female: 35,
    nin_male: 42,
    mobile_female: 48,
    mobile_male: 65,
    smartphone_female: 18,
    smartphone_male: 32,
    cash_transfer_female: 32,
    cash_transfer_male: 24,
    pension_female: 8,
    pension_male: 15,
    micropension_female: 22,
    micropension_male: 28,
    unpaid_work_female: 5.8,
    unpaid_work_male: 1.5,
    migration_female: 8,
    migration_male: 12,
    land_ownership_female: 12,
  },
  {
    state: "Katsina",
    nin_female: 32,
    nin_male: 40,
    mobile_female: 45,
    mobile_male: 62,
    smartphone_female: 15,
    smartphone_male: 28,
    cash_transfer_female: 38,
    cash_transfer_male: 26,
    pension_female: 6,
    pension_male: 12,
    micropension_female: 18,
    micropension_male: 24,
    unpaid_work_female: 6.2,
    unpaid_work_male: 1.8,
    migration_female: 6,
    migration_male: 10,
    land_ownership_female: 10,
  },
  {
    state: "Rivers",
    nin_female: 72,
    nin_male: 78,
    mobile_female: 88,
    mobile_male: 95,
    smartphone_female: 58,
    smartphone_male: 72,
    cash_transfer_female: 26,
    cash_transfer_male: 20,
    pension_female: 28,
    pension_male: 38,
    micropension_female: 52,
    micropension_male: 58,
    unpaid_work_female: 3.8,
    unpaid_work_male: 0.9,
    migration_female: 22,
    migration_male: 28,
    land_ownership_female: 32,
  },
  {
    state: "Oyo",
    nin_female: 62,
    nin_male: 70,
    mobile_female: 75,
    mobile_male: 88,
    smartphone_female: 42,
    smartphone_male: 58,
    cash_transfer_female: 30,
    cash_transfer_male: 25,
    pension_female: 18,
    pension_male: 28,
    micropension_female: 38,
    micropension_male: 45,
    unpaid_work_female: 4.2,
    unpaid_work_male: 1.1,
    migration_female: 14,
    migration_male: 20,
    land_ownership_female: 28,
  },
  {
    state: "Enugu",
    nin_female: 70,
    nin_male: 76,
    mobile_female: 82,
    mobile_male: 90,
    smartphone_female: 50,
    smartphone_male: 65,
    cash_transfer_female: 28,
    cash_transfer_male: 22,
    pension_female: 25,
    pension_male: 35,
    micropension_female: 48,
    micropension_male: 54,
    unpaid_work_female: 3.5,
    unpaid_work_male: 0.85,
    migration_female: 20,
    migration_male: 26,
    land_ownership_female: 30,
  },
  {
    state: "Osun",
    nin_female: 58,
    nin_male: 65,
    mobile_female: 70,
    mobile_male: 82,
    smartphone_female: 38,
    smartphone_male: 52,
    cash_transfer_female: 32,
    cash_transfer_male: 26,
    pension_female: 16,
    pension_male: 26,
    micropension_female: 40,
    micropension_male: 48,
    unpaid_work_female: 4.8,
    unpaid_work_male: 1.3,
    migration_female: 11,
    migration_male: 16,
    land_ownership_female: 22,
  },
  {
    state: "Kwara",
    nin_female: 54,
    nin_male: 62,
    mobile_female: 68,
    mobile_male: 80,
    smartphone_female: 35,
    smartphone_male: 50,
    cash_transfer_female: 30,
    cash_transfer_male: 24,
    pension_female: 14,
    pension_male: 24,
    micropension_female: 36,
    micropension_male: 44,
    unpaid_work_female: 5.1,
    unpaid_work_male: 1.4,
    migration_female: 10,
    migration_male: 14,
    land_ownership_female: 20,
  },
  {
    state: "Bauchi",
    nin_female: 28,
    nin_male: 36,
    mobile_female: 40,
    mobile_male: 58,
    smartphone_female: 12,
    smartphone_male: 25,
    cash_transfer_female: 40,
    cash_transfer_male: 28,
    pension_female: 5,
    pension_male: 10,
    micropension_female: 15,
    micropension_male: 20,
    unpaid_work_female: 6.5,
    unpaid_work_male: 2.0,
    migration_female: 5,
    migration_male: 8,
    land_ownership_female: 8,
  },
  {
    state: "Borno",
    nin_female: 25,
    nin_male: 32,
    mobile_female: 35,
    mobile_male: 52,
    smartphone_female: 10,
    smartphone_male: 22,
    cash_transfer_female: 42,
    cash_transfer_male: 30,
    pension_female: 4,
    pension_male: 8,
    micropension_female: 12,
    micropension_male: 18,
    unpaid_work_female: 7.0,
    unpaid_work_male: 2.2,
    migration_female: 4,
    migration_male: 6,
    land_ownership_female: 6,
  },
];

// Infrastructure data by state (facilities count)
export const INFRASTRUCTURE_DATA = [
  {
    state: "Lagos",
    childcare_rural: 245,
    childcare_urban: 1250,
    potable_water: 78,
    water_boards: 15,
    public_toilets: 350,
    school_toilets: 2800,
    water_distance: 0.5,
    electricity_hours: 18,
  },
  {
    state: "Kano",
    childcare_rural: 85,
    childcare_urban: 450,
    potable_water: 55,
    water_boards: 8,
    public_toilets: 120,
    school_toilets: 950,
    water_distance: 2.5,
    electricity_hours: 12,
  },
  {
    state: "Katsina",
    childcare_rural: 65,
    childcare_urban: 380,
    potable_water: 48,
    water_boards: 6,
    public_toilets: 95,
    school_toilets: 780,
    water_distance: 3.2,
    electricity_hours: 10,
  },
  {
    state: "Rivers",
    childcare_rural: 180,
    childcare_urban: 920,
    potable_water: 82,
    water_boards: 12,
    public_toilets: 280,
    school_toilets: 2200,
    water_distance: 0.8,
    electricity_hours: 20,
  },
  {
    state: "Oyo",
    childcare_rural: 140,
    childcare_urban: 750,
    potable_water: 70,
    water_boards: 10,
    public_toilets: 210,
    school_toilets: 1680,
    water_distance: 1.2,
    electricity_hours: 16,
  },
  {
    state: "Enugu",
    childcare_rural: 155,
    childcare_urban: 850,
    potable_water: 75,
    water_boards: 11,
    public_toilets: 240,
    school_toilets: 1900,
    water_distance: 1.0,
    electricity_hours: 17,
  },
  {
    state: "Osun",
    childcare_rural: 120,
    childcare_urban: 680,
    potable_water: 68,
    water_boards: 9,
    public_toilets: 190,
    school_toilets: 1520,
    water_distance: 1.5,
    electricity_hours: 14,
  },
  {
    state: "Kwara",
    childcare_rural: 100,
    childcare_urban: 580,
    potable_water: 62,
    water_boards: 8,
    public_toilets: 160,
    school_toilets: 1280,
    water_distance: 1.8,
    electricity_hours: 13,
  },
  {
    state: "Bauchi",
    childcare_rural: 55,
    childcare_urban: 290,
    potable_water: 42,
    water_boards: 5,
    public_toilets: 75,
    school_toilets: 600,
    water_distance: 4.5,
    electricity_hours: 8,
  },
  {
    state: "Borno",
    childcare_rural: 45,
    childcare_urban: 240,
    potable_water: 38,
    water_boards: 4,
    public_toilets: 60,
    school_toilets: 480,
    water_distance: 5.0,
    electricity_hours: 7,
  },
];

// National averages
export const NATIONAL_AVERAGES = {
  nin_female: 45,
  nin_male: 55,
  mobile_female: 62,
  mobile_male: 78,
  smartphone_female: 38,
  smartphone_male: 52,
  cash_transfer_female: 32,
  cash_transfer_male: 25,
  pension_female: 15,
  pension_male: 25,
  micropension_female: 35,
  micropension_male: 40,
  land_ownership_female: 20,
  unpaid_work_female: 4.7,
  unpaid_work_male: 1.3,
  childcare_rural: 120,
  childcare_urban: 680,
  potable_water: 65,
  water_boards: 9,
  public_toilets: 180,
  school_toilets: 1425,
  water_distance: 2.0,
  electricity_hours: 14,
  migration_female: 11,
  migration_male: 16,
};

// Function to get state-level data
export function getStateGenderData(indicator: string, state: string) {
  const stateData = STATE_GENDER_DATA.find((s) => s.state === state);
  if (!stateData) return null;
  return (stateData as any)[indicator];
}

// Function to get infrastructure data for state
export function getInfrastructureData(indicator: string, state: string) {
  const stateData = INFRASTRUCTURE_DATA.find((s) => s.state === state);
  if (!stateData) return null;
  return (stateData as any)[indicator];
}

// Get sorted states
export function getSortedStates(): string[] {
  return STATES;
}
